version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fake-gcs-server
  fake-gcs-server:
    image: "fsouza/fake-gcs-server"
    ports:
      - "4443:4443"
    volumes:
      - ${PWD}/files:/data
    command: ["-backend", "memory", "-scheme", "http", "-public-host", "gcs:4443", "-external-url", "http://gcs:4443"]
    
